name: Build Electron

# ... (your existing on:, jobs:, etc.)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean install (cross-platform)
        run: |
          # remove old installs and lockfile to avoid optional-deps install issues
          rm -rf node_modules package-lock.json || del /s /q node_modules & del package-lock.json || true
          npm install --no-optional

      - name: Build web assets
        run: npm run build:web

      # ... rest of your build/packaging steps
